          version: 2
          jobs:
            build:
              docker:
                - image: mcr.microsoft.com/dotnet/core/sdk:3.1
              steps:
                - checkout
                - run:
                    name: Restore
                    command: dotnet restore
                    working_directory: AwesomeMusicManager.AlbumService/AwesomeMusicManager.AlbumService.WebApi
                - run:
                    name: Build
                    command: dotnet build -c Release
                    working_directory: AwesomeMusicManager.AlbumService/AwesomeMusicManager.AlbumService.WebApi
                - run:
                    name: Running Tests
                    command: dotnet test
                    working_directory: AwesomeMusicManager.AlbumService/AwesomeMusicManager.AlbumService.Tests